name: Windows/Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['windows-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v3

    - run: composer install --prefer-dist --no-interaction

    - run: composer test
